// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnvnipgtydhlhgrjwzvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBudm5pcGd0eWRobGhncmp3enZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2MTU0MTAsImV4cCI6MjA3OTE5MTQxMH0.Mi0phLKYzqvMeQKEHG2DZv2D1nbQGXkjuHj5p3IHqsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});